---
apiVersion: v1
data:
  supervisord.conf: |
    [supervisord]
    # Run as a foreground process to keep the container running
    nodaemon=true

    [supervisorctl]
    serverurl = unix:///var/run/supervisor/supervisor.sock
    prompt = supervisorctl

    # https://github.com/Supervisor/supervisor/issues/480#issuecomment-145193475
    [unix_http_server]
    file = /var/run/supervisor/supervisor.sock

    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

    [program:jabber-router]
    user=jabber
    command=/usr/bin/router -c /etc/jabberd/router.xml

    [program:jabberd]
    user=jabber
    command=/usr/bin/sm -c /etc/jabberd/sm.xml

    [program:jabber-c2s]
    user=jabber
    command=/usr/bin/c2s -c /etc/jabberd/c2s.xml

    [program:jabber-s2s]
    user=jabber
    command=/usr/bin/s2s -c /etc/jabberd/s2s.xml

    [program:tomcat]
    command=/usr/libexec/tomcat/server start

    [program:httpd]
    command=/usr/sbin/httpd -D FOREGROUND

    [program:osa-dispatcher]
    command=/usr/sbin/osa-dispatcher start

    [program:taskomatic]
    command=/usr/sbin/taskomatic start

    # Not sure if this is affecting anything yet or not
    # [program:cobblerd]
    # command=/usr/sbin/cobblerd --no-daemonize
    # command=/usr/bin/python -s /bin/cobblerd --no-daemonize

    # This might be stupid but it seems to work.  Let everything start up and then start the install
    # Once done, restart the Web services and the new user creation screen appears
    [program:spacewalk-init]
    command=/bin/bash -c 'sleep 10 && spacewalk-setup --skip-fqdn-test --skip-db-install --skip-db-population --skip-services-restart --answer-file=/spacewalk-scripts/answerfile.txt && supervisorctl restart httpd && supervisorctl restart tomcat'
    priority=999
kind: ConfigMap
metadata:
  name: spacewalk-supervisord-conf
