---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacewalk
  labels:
    app: spacewalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacewalk
  template:
    metadata:
      labels:
        app: spacewalk
    spec:
      securityContext:
        runAsUser: 0
      volumes:
      - name: spacewalk-postgres-claim
        persistentVolumeClaim:
          claimName: spacewalk-postgres-claim
      - name: spacewalk-repo-claim
        persistentVolumeClaim:
          claimName: spacewalk-repo-claim
      - name: spacewalk-answerfile
        configMap:
          name: spacewalk-answerfile
      containers:
      - name: postgres
        image: spacewalk-postgres:0.2
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: spacewalk-postgres-claim
          mountPath: /var/lib/postgresql/data
      - name: adminer
        image: adminer
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      - name: spacewalk
        image: spacewalk:0.5
        imagePullPolicy: Never
        resources:
          limits:
            memory: 4096Mi
          requests:
            memory: 4096Mi
        ports:
        - containerPort: 80
          hostPort: 8000
        - containerPort: 443
          hostPort: 8443
        - containerPort: 5222
        - containerPort: 68
        - containerPort: 69
        volumeMounts:
        - name: spacewalk-repo-claim
          mountPath: /var/www/html/repo
        - name: spacewalk-answerfile
          mountPath: /tmp
