---
apiVersion: v1
data:
  answerfile.txt: |
    admin-email = root@localhost
    ssl-set-cnames = spacewalk
    ssl-set-org = Spacewalk
    ssl-set-org-unit = spacewalk
    ssl-set-city = Minneapolis
    ssl-set-state = MN
    ssl-set-country = US
    ssl-password = spacewalk
    ssl-set-email = root@localhost
    ssl-config-sslvhost = Y
    db-backend=postgresql
    db-name=postgres
    db-user=spaceuser
    db-password=spacepw
    db-host=spacewalk-db
    db-port=5432
    enable-tftp=N
kind: ConfigMap
metadata:
  name: spacewalk-answerfile
